name: wikibus-www
services:
  appserver:
    type: node
    port: 8080
    ssl: true
    command: npm start -- --disable-host-check --host 0.0.0.0
    ssl: true
proxy:
  appserver:
    - wikibus.lndo.site:8080
