[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  API_LIBRARY = "https://sources.wikibus.org/"
  API_DATA_SHEETS = "https://sheets.wikibus.org/"
  API_FALLBACK = "https://www.wikbus.org/"

[context.branch-deploy]
  command = "npm run build"

[context.branch-deploy.environment]
  API_LIBRARY = "https://sources.test.wikibus.org/"
  API_DATA_SHEETS = "https://sheets.wikibus.org/"
  API_FALLBACK = "https://www.wikbus.org/"
