[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  API_ROOT = "https://bff.test.wikibus.org/"
  AUTH0_CLIENT_ID = "A4j5Tdmq1zskLpmawVgB6OABUQr4A9fu"

[context.develop.environment]
  AUTH0_CLIENT_ID = "A4j5Tdmq1zskLpmawVgB6OABUQr4A9fu"

[context.master.environment]
  API_ROOT = "https://bff.wikibus.org/"
  AUTH0_CLIENT_ID = "Goc6AyTupeYzcatX3Xdrt0lLphv1OTW1"
