declare module '*.scss'
declare module '*.css'
declare module 'feather-icon-literals'
declare module '@lit-element-bootstrap/alert'
declare module '@lit-element-bootstrap/modal'
declare module '@lit-element-bootstrap/button'
declare module '@lit-element-bootstrap/dropdown'
